all:
	pdflatex *.tex
	pdflatex *.tex

#image2pdf:
#	epstopdf logos/ybang.eps
#	epstopdf logos/ylogo.eps
clean:
	rm -rf *.aux *.log *.nav *.snm *.toc *.out *.vrb

cleanall:
	rm -rf *.aux *.log *.nav *.snm *.pdf *.toc *.out *.vrb
